spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      show_sql: true

  h2:
    console:
      enabled: true

  data:
    redis:
      host: localhost
      port: 6379
      password:

jwt:
  secret: XUKemfiZfrEWLtykdkjfeliwjfd59YLt5XXXkAdqZu33
  token:
    access-expiration-time: 60000    # 1분
    refresh-expiration-time: 180000   # 3분

server:
  port: 8080



