spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      show_sql: true

  h2:
    console:
      enabled: true

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

jwt:
  secret : SecretKeySizeMustHaveSizeBigger256BitsSoSecretKeyLengthLong
  refreshSecret: ReFreshSecretKeySizeMustHaveSizeBigger256BitsSoSecretKeyLengthLong



