spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/fastboard
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show_sql: true


  data:
    redis:
      host: localhost
      port: 6379
      password:

jwt:
  secret: XUKemfiZfrEWLtykdkjfeliwjfd59YLt5XXXkAdqZu33
  token:
    access-expiration-time: 180000    # 3분
    refresh-expiration-time: 6000000   # 10분

file:
  dir: C:\Users\ChangHoMoon\images

server:
  port: 8080



