spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      show_sql: true

  h2:
    console:
      enabled: true

jwt:
  secret: XUKemfiZfrEWLtykdkjfeliwjfd59YLt5XXXkAdqZu33
  token:
    access-expiration-time: 1800000    # 30분
    refresh-expiration-time: 604800000   # 7일

server:
  port: 8080



